name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/atut_devops:latest
          ${{ secrets.DOCKER_USERNAME }}/atut_devops:${{ github.sha }}
    
    - name: Deploy to OVHcloud via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.OVHCLOUD_HOST }}
        username: ${{ secrets.OVHCLOUD_USERNAME }}
        key: ${{ secrets.OVHCLOUD_SSH_PRIVATE_KEY }}
        script: |
          # Login to Docker Hub
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          # Pull the latest Docker image
          docker pull ${{ secrets.DOCKER_USERNAME }}/atut_devops:latest || true

          # Ensure chat.db exists
          if [ ! -f "$(pwd)/chat.db" ]; then
            touch "$(pwd)/chat.db"
          fi
          
          # Stop and remove existing container if it exists
          docker stop atut_devops || true
          docker rm atut_devops || true
          
          # Run the new container
          docker run -d \
            --name atut_devops \
            -p 8000:8000 \
            -v   "$(pwd)/chat.db:/app/chat.db" \ 
            ${{ secrets.DOCKER_USERNAME }}/atut_devops:latest
