name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/chatapp:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/chatapp:${{ github.sha }}
    
    - name: Deploy to OVHcloud via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.OVHCLOUD_HOST }}
        username: ${{ secrets.OVHCLOUD_USERNAME }}
        key: ${{ secrets.OVHCLOUD_SSH_PRIVATE_KEY }}
        script: |
          # Pull the latest Docker image
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/chatapp:latest
          
          # Stop and remove existing container if it exists
          docker stop chatapp || true
          docker rm chatapp || true
          
          # Run the new container
          docker run -d \
            --name chatapp \
            -p 8000:8000 \
            -v ./chat.db:/app/chat.db \
            ${{ secrets.DOCKER_USERNAME }}/chatapp:latest
